# .air.toml

[build]
cmd = "go build -o ./bin/main ."
bin = "bin/main"
full_bin = "./bin/main"
delay = 1000 # ms
log = "air.log"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "bin"]
exclude_file = ["air.log", "README.md"]
exclude_regex = ["^examples"]
# stop_on_error = true
# send_interrupt = false
# kill_signal = "SIGKILL"

[dev]
cmds = [
    "echo 'running...'",
    "./bin/main"
]

[log]
color = true
